<a href="https://colab.research.google.com/github/sumukhasrivatsa/PyTorch-Learnings/blob/main/Backpropogation%20through%202%20different%20networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import torch
import random
import numpy as np
seed=420
a=[]
b=[]
images=[]
print(type(a))
random.seed(69)
for i in range(1000):
  
  a.append([random.randint(1,100),random.randint(1,10),random.randint(1,1009),random.randint(1,1088)])
  b.append(random.randint(1,11))
  images.append(np.random.randint(0,255,(20,20)))


#converting to np array
a=np.array(a)
print(type(a))
b=np.array(b)
#converting to a torch tensor
a=torch.from_numpy(a)

print(type(a))
b=torch.from_numpy(b)

#changing the type of the torch cuz grad works only on float32

a=a.type(dtype=torch.float32)
a.requires_grad=True
print(type(a))

b=b.type(dtype=torch.float32)
b.requires_grad=True
print(a)

#making a class for neural network
import torch.nn as nn

class netA(nn.Module):
  def __init__(self):
    super(netA,self).__init__()
    self.l1=nn.Linear(4,4)
    
    print(type(self.l1))
    self.l2=nn.Linear(4,4)
    self.l3=nn.Linear(4,4)
    


  def forward(self, x):
    x=self.l1(x)
    
    x=self.l2(x)
    x=self.l3(x)
    return x

obj=netA()
yhat=obj.forward(a)
print(yhat[0])
y=torch.mean(yhat)
y.backward()






  







In [46]:

noise=[]
noise.append([random.randint(1,100),random.randint(1,10),random.randint(1,1009),random.randint(1,1088),random.randint(1,1088),random.randint(1,1088)])
noise=np.asarray(noise,float)
noise=torch.from_numpy(noise)
noise=noise.type(dtype=torch.float32)

class noise_to_matrix(nn.Module):
  def __init__(self):
    super(noise_to_matrix,self).__init__()
    self.l1=nn.Linear(6,4)
    self.l2=nn.Linear(4,4)
    self.l3=nn.Linear(4,4)

  def forward(self,noise):
    noise=self.l1(noise)
    noise=self.l2(noise)
    matrix=self.l3(noise)

    return matrix


obj=noise_to_matrix()
mat=obj.forward(noise)
mat=torch.reshape(mat,(2,2))
print(mat)

for name, param in obj.named_parameters():
  print(name,param)




#creating a random image
image=np.random.randint(0,255,(2,2))
image=torch.from_numpy(image)
image=image.type(dtype=torch.float32)

print(image)

image_temp=image

image=image*mat

#creating a network to convolve

print(image)

image_for_nn=torch.flatten(image)

class image_to_loss(nn.Module):
  def __init__(self):
    super(image_to_loss,self).__init__()
    self.l1=nn.Linear(4,4)
    self.l2=nn.Linear(4,2)
    self.l3=nn.Linear(2,1)

  def forward(self,img):
    noise=self.l1(img)
    noise=self.l2(noise)
    output=self.l3(noise)

    return output


obj1=image_to_loss()
yhat=obj1.forward(image_for_nn)
loss=yhat-11
loss.backward()
print(loss)
optimizer = torch.optim.SGD(obj.parameters(), lr=0.01, momentum=0.9)
optimizer.step()

for name, param in obj.named_parameters():
  print(name,param)

  












tensor([[-79.4743, -54.4934],
        [ 51.3098, -98.1225]], grad_fn=<ReshapeAliasBackward0>)
l1.weight Parameter containing:
tensor([[ 0.1233, -0.0757, -0.3559, -0.0195,  0.1845, -0.2578],
        [ 0.2356, -0.0958,  0.1382,  0.0702, -0.0058, -0.0226],
        [ 0.1147, -0.0500, -0.0372,  0.1782,  0.2970, -0.0825],
        [ 0.0719, -0.2494,  0.0414,  0.2188, -0.1176,  0.1644]],
       requires_grad=True)
l1.bias Parameter containing:
tensor([-0.1994, -0.3753,  0.1785,  0.0494], requires_grad=True)
l2.weight Parameter containing:
tensor([[-0.4178, -0.2737, -0.4337, -0.2776],
        [-0.4719, -0.1556,  0.2299,  0.0104],
        [-0.4506, -0.2203,  0.4314,  0.2588],
        [-0.4920,  0.4905, -0.2603,  0.3982]], requires_grad=True)
l2.bias Parameter containing:
tensor([-0.1835,  0.2097, -0.0732, -0.1898], requires_grad=True)
l3.weight Parameter containing:
tensor([[ 0.2762, -0.2292, -0.1438, -0.2588],
        [ 0.3585, -0.1895, -0.0421, -0.2239],
        [ 0.0681, -0.1049,  0.1619,  0.